version: "3.8"
services:
  web:
    depends_on: 
      - api
    build: ./frontend
    ports:
      - 5173:5173
    environment:
      VITE_API_URL: ${VITE_API_URL}

    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync

  api: 
    # depends_on: 
    #   - db

    build: ./backend

    ports: 
      - 8000:8000

    env_file:
      - ./backend/.env

    environment: 
      DB_URL: ${DB_URL}

    develop:
      watch:
        - path: ./backend/package.json
          action: rebuild
        - path: ./backend/package-lock.json
          action: rebuild

        - path: ./backend
          target: /app
          action: sync

#   Removed the db servive as I using MongoDB Atlas
#   db:
#     image: mongo:latest

#     ports:
#       - 27017:27017

#     volumes:
#       - anime:/data/db

# volumes:
#   anime: